# screen units mean screen is 1.0 wide and 1.0 high

[game]
gravity = 5 #In arbitrary units
horizontal_cage_padding = 0.02 #How far outside of the visible screen the player position can go; in screen units
smoke_puff_spread = 0.01 #Spread of smoke puffs off player bullet trajectory; in screen units
enable_mouse = true
cloud_count = 3
ufo_hit_invul_duration = 0.3 #How long ufos turn white and invulnerable after a hit (in Seconds)
day_length = 20.0 #game Day length in real seconds
